# Site settings
title: Travel Blog
email: stovechan@yahoo.com
description: My ASEAN rest and relax travelling.
baseurl: "/travel-blog"
twitter_username: Chanmarvin2
avatar: "" # Set footer avatar
paginate: 3

# Build settings
markdown: kramdown
permalink: /:title

# Default Settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Stove and Marvin" # Set default author name
      categories: "Lokasi"
      layout: "post"
      comments: true
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
